### ISSUE TITLE
Pre-built llama.cpp binaries: Metal fails to compile on macOS 26 Tahoe (M5)

### ISSUE THREAD

**Issue by lightoshadow** [PrismML-Eng/Bonsai-demo#93]
## Environment
- macOS Thaoe 26.3.1
- Apple M5, 24 GB unified memory
- Pre-built binaries (b9591-62061f9), Ternary-Bonsai-27B-Q2_0

## Error

Running `./scripts/run_llama.sh -p "Hello"` fails with metal compilation errors followed by repeated Out Of Memory crashes.

```
ggml_metal_library_init_from_source: error compiling source
ggml_metal_device_init: - the tensor API is not supported in this environment - disabling
ggml_metal_synchronize: error: command buffer 0 failed with status 5
error: Insufficient Memory (00000008:kIOGPUCommandBufferCallbackErrorOutOfMemory)
```

the model produces no output.

## Workaround 

`BONSAI_NGL=0 ./scripts/run_llama.sh -p "Hello" runs on CPU and works, just slow.`

**Comment by khosravipasha** [comment]
Hmm, that's odd, could you try building from source, there is an script for that.
We have tested on M5 macs and it was okay, maybe had lots of applications open when you ran it? For Ternary might need closer to 10GB free, check if the llama.cpp is allocation the full context, that might be the issue.

`BONSAI_NGL=0` runs on CPU only so that's why its slower. If that works then not sure getting "Out Of Memory crashes" in the other cases.

**Comment by ayobamiseun** [comment]
Some triage data points that should narrow this down — I can't repro on an M3, and the failure looks specific to the M5's tensor-API path, not to macOS 26 in general.

**Same binaries work on M3 Pro + macOS 26.5.2.** Same pre-built tag (`prism-b9591-62061f9`), Ternary-Bonsai-27B-Q2_0, full GPU offload (`-ngl 99 -fa 1`) — runs clean, 78.6 t/s pp512 / 12.6 t/s tg128 (details in #108). The relevant init log on M3:

```
ggml_metal_device_init: tensor API disabled for pre-M5 and pre-A19 devices
ggml_metal_library_init: using embedded metal library
```

So pre-M5 devices never compile Metal source at runtime — they load the embedded metallib. Your M5 takes a different path: ggml probes the tensor API by compiling MSL at runtime, and that compile is what's failing (`ggml_metal_library_init_from_source: error compiling source`).

**This is a known ecosystem-wide M5 + macOS 26.2/26.3 issue**, hitting every ggml-based project: the runtime compile trips a `static_assert` (bfloat/half type mismatch) in the OS's MetalPerformancePrimitives headers (`MPPTensorOpsMatMul2dImpl.h`), which got stricter in recent macOS 26 point releases. Same signature in [ollama#15594](https://github.com/ollama/ollama/issues/15594), [ollama#15862](https://github.com/ollama/ollama/issues/15862), [whisper.cpp#3722](https://github.com/ggml-org/whisper.cpp/issues/3722), and [lmstudio#2040](https://github.com/lmstudio-ai/lmstudio-bug-tracker/issues/2040).

**Suggested workaround — keep the GPU, skip the tensor-API probe:**

```bash
GGML_METAL_TENSOR_DISABLE=1 ./scripts/run_llama.sh -p "Hello"
```

I verified the shipped `libggml-metal.dylib` in this release honors `GGML_METAL_TENSOR_DISABLE`. This makes the M5 behave like pre-M5 devices (embedded library, no runtime compile) — you lose the Neural Accelerator prefill boost but keep full Metal speed, which should be far faster than `BONSAI_NGL=0`.

**On the OOM half:** that may be a second, independent problem. `run_llama.sh` uses `-c 0` (auto-fit), and the 27B supports 256k context, so on 24 GB the auto-fit can size the KV cache right up to the working-set limit — and the earlier failed tensor-API state may have already fragmented/consumed GPU memory. If OOMs persist even with the workaround above, try pinning a modest context (extra args pass straight through to llama-cli and override the default):

```bash
GGML_METAL_TENSOR_DISABLE=1 ./scripts/run_llama.sh -c 16384 -p "Hello"
```

If the workaround checks out on your machine, a possible repo-side fix would be for `run_llama.sh`/`start_llama_server.sh` to export `GGML_METAL_TENSOR_DISABLE=1` on affected macOS builds (or at least mention it in the README troubleshooting section) until the upstream header issue is resolved — happy to send a PR for whichever the maintainers prefer.

**Comment by lightoshadow** [comment]
> Hmm, that's odd, could you try building from source, there is an script for that. We have tested on M5 macs and it was okay, maybe had lots of applications open when you ran it? For Ternary might need closer to 10GB free, check if the llama.cpp is allocation the full context, that might be the issue.
> 
> `BONSAI_NGL=0` runs on CPU only so that's why its slower. If that works then not sure getting "Out Of Memory crashes" in the other cases.

I tried recompiling with the `build_mac.sh`script, now if i run `run_llama.sh -c 0` my mac freezes and i have to restart it using the power button. While if i run it with smaller context, eg `-c 8192` it runs. I think there's a bug which allocates too much memory. and completly hogs the OS.

**Comment by khosravipasha** [comment]
> I tried recompiling with the build_mac.shscript, now if i run run_llama.sh -c 0 my mac freezes and i have to restart it using the power button.

Yeah seems running `-c 0` might not be the best idea. Trying to fix memory issue here https://github.com/PrismML-Eng/Bonsai-demo/pull/120

**Comment by khosravipasha** [comment]
> Metal fails to compile on macOS 26 Tahoe (M5)

@lightoshadow is the original issue resolved? for failing to complie, did you need to make any changes? closing this for now, feel free to open if its not fixed.

**Comment by lightoshadow** [comment]
After recompiling it works with either `GGML_METAL_TENSOR_DISABLE=1 ./scripts/run_llama.sh -c 16384 -p "Hello"`or `GGML_METAL_TENSOR_DISABLE=0 ./scripts/run_llama.sh -c 16384 -p "Hello"`, the crashing was related to `-c 0` i believe

**Comment by lightoshadow** [comment]
I've also run some benchmarks, could i open a pull request for that?

**Comment by khosravipasha** [comment]
> I've also run some benchmarks, could i open a pull request for that?

sure would be happy to take a PR.

For context size I am trying to avoid -c 0 and do based on memory available, kidna like this here:
https://github.com/PrismML-Eng/Bonsai-demo/pull/120
