### PR TITLE
setup.sh: skip MLX nax kernels on the Metal 4.1 toolchain (Xcode 27)

### PR DESCRIPTION
**Pull request by AleksMeshkov**
## Problem

On Xcode 27 (Metal 4.1), `./setup.sh` aborts partway through: `uv pip install -e mlx/` fails and takes the whole script with it, leaving the MLX backend uninstalled. llama.cpp/GGUF is unaffected.

The prism fork's Metal-4 "nax" sources don't compile with the Metal 4.1 shader compiler:

```
mlx/backend/metal/kernels/steel/attn/nax.h:574:12: error: reference to type 'thread dtype_frag_t<...>'
    could not bind to an lvalue of type 'dtype_frag_t<...>'
mlx/backend/metal/kernels/steel/utils/integral_constant.h:19:29: error: conflicting address space
    qualifiers are provided between types 'const constant T' and 'const thread int'
...
20 errors generated.
make[2]: *** [mlx/backend/metal/kernels/steel_attention_nax.air] Error 1
```

`mlx/backend/metal/kernels/CMakeLists.txt:158` builds those kernels whenever the toolchain reports `__METAL_VERSION__ >= 400` and the SDK is `>= 26.2`. Xcode 27 reports 410 / SDK 27.0, so they're enabled and the build dies. `origin/prism` has no newer commit that fixes it.

## Fix

The version is probed by running `metal -E` (`mlx/CMakeLists.txt:207`), and that probe honours `-mmacosx-version-min`. Pinning `CMAKE_OSX_DEPLOYMENT_TARGET=15.0` makes it report 320, so the kernel list takes its `MLX_METAL_NO_NAX` branch:

```
15.0 -> 320
26.0 -> 400
26.2 -> 400
```

`setup.sh` now probes the version itself and applies that only at 410+; older toolchains keep the path they already take. Below M5 nothing is lost — nax targets the neural accelerators and never dispatches on earlier chips.

`BONSAI_MLX_NAX=1` forces the kernels back on (for M5, once the fork compiles under Metal 4.1); `=0` forces them off. If the probe returns nothing usable, the decision is left to CMake as before.

## Caveat

This is a workaround, not a fix. On M5 it disables exactly the kernels nax exists for — the fork's `nax.h` / `integral_constant.h` still need to be made Metal 4.1-clean. Worth a separate issue against `PrismML-Eng/mlx`.

## Testing

macOS 27.2 / Xcode 27.0 (Metal 32023.921, `__METAL_VERSION__` 410) / M2 Pro:

- before: `setup.sh` exits 1 at the MLX build
- after: build succeeds, `mlx 0.31.2.dev20260919+10b5fe43` imports and runs a 512×512 matmul on the GPU
- decision logic exercised standalone on all four paths — auto, `BONSAI_MLX_NAX=1`, `=0`, and a failed probe — no aborts under `set -e`; `sh -n setup.sh` clean

`BONSAI_MLX_NAX` is documented in `environment_variables.md`.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by khosravipasha** [comment]
🤖 Answering on behalf of the maintainers

Thanks for investigating this and testing a workaround! Upstream MLX already had the Metal 4.1 compiler fix, but our fork was missing it. We've now merged that backport in [PrismML-Eng/mlx#13](https://github.com/PrismML-Eng/mlx/pull/13) (`752b2d1`), addressing the address-space errors directly without disabling the nax kernels.

Could you try the updated fork without this workaround and let us know whether it fixes your build? A few gotchas for validation:

- `setup.sh` reuses an existing `mlx/` checkout without updating it. Make sure your checkout includes `752b2d1` (preserving any local changes).
- Setup also skips the build if MLX and a sufficiently recent mlx-lm are already installed. Rebuild/reinstall the updated fork explicitly rather than relying on rerunning setup alone.
- Remove the workaround's `-DCMAKE_OSX_DEPLOYMENT_TARGET=15.0` from `CMAKE_ARGS` and any cached build configuration. Setting `BONSAI_MLX_NAX=1` alone doesn't undo a cached deployment target. A clean build is the clearest check that the formerly failing nax kernels actually compile.

Repeating your GPU matmul check after that build would be helpful. Your M2 Pro can validate compilation and the normal GPU path; it won't exercise M5's nax execution path. If it still fails, please share the MLX commit, active Metal compiler/SDK versions, and the first compiler error. Thanks again for catching this!

**Comment by khosravipasha** [comment]
🤖 Answering on behalf of the maintainers

Thanks again for investigating this and contributing the workaround! We are closing this as superseded by the compiler fix merged in https://github.com/PrismML-Eng/mlx/pull/13, which addresses the build errors without disabling nax kernels.

Please try the updated MLX fork, following the checkout/rebuild and cached deployment-target notes above. If it still does not work on your setup, please reopen this PR (or leave a comment and we can reopen it) with the remaining error. We appreciate your testing!
